export const MESSAGE_CLASSES = {
  GREEN_FLAG: 'GREEN_FLAG',
  RED_FLAG: 'RED_FLAG',
}

export const MESSAGE_TYPES = {
  NOTIFICATION: 'NOTIFICATION',
  ERROR: 'ERROR',
  JOIN_ROOM: 'JOIN_ROOM',
}
export const MOUSE_EVENTS = {
  CLIENT_DOWN: 'C_MOUSE_DOWN',
  CLIENT_MOVE: 'C_MOUSE_MOVE',
  SERVER_DOWN: 'S_MOUSE_down',
  SERVER_MOVE: 'S_MOUSE_MOVE',
}
